settings:
    notify: false
    textcommand_prefix: "!"
    token: "<bot_token>" 
    guilds:
        "<server_id>":
            name: "Макси"
            log_channel: "<log_channel_id>"
            owners: 
            - "<owner_id>"
            roles:
                staff: 
                - "<staff_role>"
                blacklisted: [] #"<blacklisted_role_id>"
    client:
        id: "<bot_client_id>"
        secret: "<bot_client_secret>"
